# Generated by Django 5.0.4 on 2024-06-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
