# Generated by Django 5.0.4 on 2024-06-27 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0002_company_description2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description2',
        ),
    ]
