# Generated by Django 5.0.4 on 2024-06-27 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0003_remove_company_description2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
