# Generated by Django 5.0.4 on 2024-06-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0004_company_description2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='company',
            name='description3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
