# Generated by Django 5.0.4 on 2024-06-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0005_alter_company_options_company_description3'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description4',
            field=models.TextField(blank=True, null=True),
        ),
    ]
