# Generated by Django 5.0.4 on 2024-06-27 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0006_company_description4'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description5',
            field=models.TextField(blank=True, null=True),
        ),
    ]
