# Generated by Django 5.0.4 on 2024-06-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_1', '0007_company_description5'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description6',
            field=models.TextField(blank=True, null=True),
        ),
    ]
